#!/usr/bin/env python
"""
HCN...HCl dimer, xlocal min: CNEO-DFT/BP86 aug-cc-pVQZ re-optimization, Hessian and harmonic frequencies

System           : hydrogen cyanide / hydrogen chloride dimer,
                   linear H-C#N...Cl-H, halogen bonded, Cl the donor and N the acceptor (local minimum)
Method           : CNEO-DFT (pyscf.neo.CDFT), electronic xc = BP86, no EPC
Quantum nuclei   : every hydrogen (atoms 0 and 3), protonic basis PB4-D
Electronic basis : aug-cc-pvqz
Starting point   : substituted: February run drifted apart (N..Cl 10.4 A, NOT finished: killed after 639 steps); starting from the PBE/aug-cc-pVQZ halogen-bonded geometry; the February 2026 BP86/aug-cc-pVQZ xlocal_min run found no bound complex, so this input tests the BP86 halogen bond afresh

Workflow
  1. tight CNEO-DFT SCF at the starting geometry
  2. geomeTRIC re-optimization with the analytic CNEO-DFT gradient
     (GAU_TIGHT criteria, net force/torque projected out, grid response on)
  3. single-point SCF at the optimized geometry
  4. analytic CNEO-DFT Hessian (300 CPHF iterations, level-shift retry)
  5. translational sum-rule check of the Hessian and repair of its diagonal
     blocks; harmonic frequencies from the raw and the repaired Hessian
  6. summary

Why the repair: the February 2026 HCN...HCl Hessians violated the
translational sum rule on the chlorine row by 0.07 to 0.4 Eh/Bohr^2 (other
atoms <= 1e-3), which produced spurious imaginary bending modes of 67i to
350i cm^-1 at aug-cc-pVDZ and aug-cc-pVQZ. Resetting each diagonal block to
minus the sum of its off-diagonal blocks removed them and made the spectra
agree across bases to a few cm^-1.

Needs the theorychemyang/pyscf fork at version 2.14 or later and geomeTRIC.
Outputs next to the log: <stem>.traj.xyz, <stem>.opt.xyz, <stem>.hessian.npz.

Generated by make_inputs.py on 2026-09-18 from geometries/hcn_hcl_start_geometries.xyz;
edit the generator, not this file.
"""
import os
import sys
import time

import numpy
import pyscf
from pyscf import neo
from pyscf.geomopt.geometric_solver import GeometryOptimizer
from pyscf.hessian.thermo import rotation_const, _get_rotor_type

# ----------------------------------------------------------------------------
# Settings
# ----------------------------------------------------------------------------
XC = 'bp86'                     # electronic exchange-correlation functional (PySCF/libxc keyword)
EPC = None                     # electron-proton correlation functional; None = off
BASIS = 'aug-cc-pvqz'               # electronic basis on every atom
NUC_BASIS = 'pb4d'             # protonic basis
QUANTUM_NUC = ['H']            # every hydrogen nucleus treated quantum mechanically
CHARGE = 0
VERBOSE = 4
MAX_MEMORY = int(os.environ.get('PYSCF_MAX_MEMORY', 16000))   # MB

# SCF. The nuclear-gradient error is first order in the SCF orbital-gradient
# residual, so the SCF has to be converged well below the optimizer criteria.
SCF_CONV_TOL = 1e-11           # Eh
SCF_CONV_TOL_GRAD = 1e-6       # orbital gradient; the default sqrt(conv_tol) would be 3e-6
SCF_MAX_CYCLE = 200
CPSCF_CONV_TOL = 1e-9          # coupled-perturbed SCF for the Hessian (default 1e-8)
GRID_LEVEL = 5                 # electronic DFT grid (PySCF default 3); set on components['e']
GRID_RESPONSE = True           # grid-weight derivatives in the gradient (only allowed with EPC off)

# Geometry optimization (geomeTRIC through pyscf.geomopt)
OPT_MAX_STEPS = 200            # a 5-atom complex that is not done in 200 steps is stuck in noise
OPT_PARAMS = {
    'convergence_set': 'GAU_TIGHT',   # grms 1e-5, gmax 1.5e-5 Eh/Bohr; drms 4e-5, dmax 6e-5 Angstrom
    'convergence_energy': 1e-8,       # Eh, overrides the set's 1e-6
    'subfrctor': 2,                   # always project net force and torque out of the gradient
}
STOP_IF_OPT_FAILS = True       # do not spend a Hessian on an unconverged geometry

# The CNEO coupled-perturbed equations are solved with PySCF's Krylov solver,
# which raises RuntimeError when it reaches max_cycle. Every February 2026
# Hessian that failed did so exactly there (100 iterations): all aug-cc-pVQZ
# runs and every bent isomer. Allow far more iterations and, if the solver
# still fails, retry once with a level shift on the preconditioner
# (a convergence aid that does not change the converged solution).
HESS_MAX_CYCLE = 300           # CNEO-CPHF Krylov iterations (fork default 100)
HESS_LEVEL_SHIFT = 0.0         # Eh, added to the orbital-energy denominators
HESS_RETRY_LEVEL_SHIFT = 0.2   # Eh, used for the one automatic retry

# Hessian repair: enforce the translational sum rule sum_q H(p,q) = 0 by
# resetting each diagonal block. The frequency tables below use the repaired
# Hessian; the raw spectrum is printed alongside for comparison.
SUM_RULE_REPAIR = True

STEM = os.path.splitext(os.path.basename(__file__))[0]

# Starting geometry, Angstrom, atom order H C N H Cl.
# February 2026 BP86/aug-cc-pVQZ xlocal_min: substituted: February run drifted apart (N..Cl 10.4 A, NOT finished: killed after 639 steps); starting from the PBE/aug-cc-pVQZ halogen-bonded geometry.
START_GEOM = """
H       -0.00000000      -0.00000000       3.99642405
C       -0.00000000       0.00000000       2.89701015
N       -0.00000000       0.00000000       1.73919876
H        0.00000000      -0.00000000      -3.05214280
Cl       0.00000000       0.00000000      -1.73659354
"""


# ----------------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------------
def banner(title):
    line = '-' * 72
    print(f'\n{line}\n{title}\n{line}', flush=True)


def build_mol(atom):
    return neo.M(atom=atom, basis=BASIS, nuc_basis=NUC_BASIS,
                 quantum_nuc=QUANTUM_NUC, charge=CHARGE, unit='Angstrom',
                 verbose=VERBOSE, max_memory=MAX_MEMORY)


def build_mf(mol):
    mf = neo.CDFT(mol, xc=XC, epc=EPC)
    mf.conv_tol = SCF_CONV_TOL
    mf.conv_tol_grad = SCF_CONV_TOL_GRAD
    mf.max_cycle = SCF_MAX_CYCLE
    mf.conv_tol_cpscf = CPSCF_CONV_TOL
    mf.components['e'].grids.level = GRID_LEVEL
    return mf


def geometry_lines(symbols, coords_ang):
    return [f'{s:<2s} {x:18.10f} {y:18.10f} {z:18.10f}'
            for s, (x, y, z) in zip(symbols, coords_ang)]


def write_xyz(path, symbols, coords_ang, comment):
    with open(path, 'w') as fh:
        fh.write(f'{len(symbols)}\n{comment}\n')
        fh.write('\n'.join(geometry_lines(symbols, coords_ang)) + '\n')


def quantum_nuclei(mol):
    idx = sorted(int(k[1:]) for k in mol.components if k.startswith('n'))
    return [f'{mol.atom_pure_symbol(i)}{i}' for i in idx]


def translational_sum_rule(hess):
    """Per-atom max |sum_q H(p,q,x,y)| in Eh/Bohr^2; exactly zero for an exact Hessian."""
    return numpy.abs(hess.sum(axis=1)).reshape(hess.shape[0], -1).max(axis=1)


def enforce_translational_sum_rule(hess):
    """Reset each diagonal block H(p,p) = -sum_{q!=p} H(p,q), then re-symmetrize."""
    natm = hess.shape[0]
    fixed = hess.copy()
    for p in range(natm):
        off = hess[p].sum(axis=0) - hess[p, p]
        fixed[p, p] = -off
    return 0.5 * (fixed + fixed.transpose(1, 0, 3, 2))


def harmonic_frequencies(hess_obj, mol, hess):
    """All 3N harmonic frequencies in cm^-1, ascending; negative = imaginary.

    Nothing is projected out, so 5 (linear) or 6 (non-linear) modes are
    numerically ~0 and represent translations/rotations. Masses are
    mol.mass, i.e. the CNEO nuclear masses used in the SCF."""
    res = hess_obj.harmonic_analysis(mol, hess, exclude_trans=False, exclude_rot=False,
                                     imaginary_freq=False, intensity=False)
    return numpy.sort(numpy.asarray(res['freq_wavenumber'], dtype=float))


def split_tr(freqs, ntr):
    order = numpy.argsort(numpy.abs(freqs))
    return set(order[:ntr]), numpy.sort(freqs[order[ntr:]])


def fmt_modes(fs):
    return ', '.join((f'{-f:.1f}i' if f < 0 else f'{f:.1f}') for f in fs)


# ----------------------------------------------------------------------------
# Run
# ----------------------------------------------------------------------------
t_start = time.time()
print(STEM)
print(f'pyscf {pyscf.__version__} from {os.path.dirname(pyscf.__file__)}')
try:
    import geometric
    print(f'geometric {geometric.__version__}')
except Exception:                                       # version string is cosmetic
    pass
print(f'numpy {numpy.__version__}; threads {pyscf.lib.num_threads()}; max_memory {MAX_MEMORY} MB')

banner('1. INITIAL SCF AT THE STARTING GEOMETRY')
mol = build_mol(START_GEOM)
mf = build_mf(mol)
e_start = mf.kernel()
if not mf.converged:
    sys.exit('initial SCF did not converge; stopping')
print(f'E(start) = {e_start:.10f} Eh')

banner('2. GEOMETRY OPTIMIZATION (geomeTRIC)')
grad = mf.nuc_grad_method()
grad.grid_response = GRID_RESPONSE
trajectory = []                                          # (step, E, |grad|, coords in Bohr)


def record_step(envs):
    trajectory.append((envs['self'].cycle, float(envs['energy']),
                       float(numpy.linalg.norm(envs['gradients'])),
                       numpy.array(envs['coords'], dtype=float)))


opt = GeometryOptimizer(grad)
opt.callback = record_step
opt.max_cycle = OPT_MAX_STEPS
opt.params = dict(OPT_PARAMS)
t0 = time.time()
mol_eq = opt.kernel()
n_steps = len(trajectory)
print(f'optimizer converged: {opt.converged}   gradient evaluations: {n_steps}   '
      f'wall {time.time() - t0:.0f} s')

symbols = [mol_eq.atom_pure_symbol(i) for i in range(mol_eq.natm)]
coords_eq = mol_eq.atom_coords(unit='ANG')
with open(f'{STEM}.traj.xyz', 'w') as fh:
    for step, e, gnorm, xyz_bohr in trajectory:
        fh.write(f'{len(symbols)}\nstep {step} E={e:.10f} Eh |grad|={gnorm:.3e} Eh/Bohr\n')
        fh.write('\n'.join(geometry_lines(symbols, xyz_bohr * pyscf.lib.param.BOHR)) + '\n')
write_xyz(f'{STEM}.opt.xyz', symbols, coords_eq,
          f'{XC} {BASIS} pb4d optimized geometry, converged={opt.converged}')
if trajectory:
    print(f'last step: E = {trajectory[-1][1]:.10f} Eh   |grad| = {trajectory[-1][2]:.3e} Eh/Bohr')
print('optimized geometry (Angstrom):')
print('\n'.join('  ' + line for line in geometry_lines(symbols, coords_eq)))
r_NCl = float(numpy.linalg.norm(coords_eq[2] - coords_eq[4]))
r_NH = float(numpy.linalg.norm(coords_eq[2] - coords_eq[3]))
r_HCl = float(numpy.linalg.norm(coords_eq[0] - coords_eq[4]))
print(f'key distances (Angstrom): N...Cl {r_NCl:.3f}   N...H(Cl) {r_NH:.3f}   H(C)...Cl {r_HCl:.3f}')
if r_NCl > 6.0:
    print('WARNING: the monomers have separated by more than 6 Angstrom; this is not a bound complex')
if not opt.converged:
    print(f'WARNING: geomeTRIC did not converge within {OPT_MAX_STEPS} steps under {OPT_PARAMS}')
    if STOP_IF_OPT_FAILS:
        sys.exit('stopping before the Hessian; set STOP_IF_OPT_FAILS = False to proceed anyway')

banner('3. SINGLE POINT AT THE OPTIMIZED GEOMETRY')
new_mol = build_mol([[s, c] for s, c in zip(symbols, coords_eq)])
new_mf = build_mf(new_mol)
e_sp = new_mf.kernel()
if not new_mf.converged:
    sys.exit('single-point SCF at the optimized geometry did not converge; stopping')
print(f'E(optimized) = {e_sp:.10f} Eh')

banner('4. ANALYTIC CNEO-DFT HESSIAN')
t0 = time.time()
run_hessian = new_mf.Hessian()
run_hessian.max_cycle = HESS_MAX_CYCLE
run_hessian.level_shift = HESS_LEVEL_SHIFT
run_hessian.verbose = 4                                  # logs 'krylov cycle N  r = ...'
try:
    hess_raw = run_hessian.kernel()                      # (natm, natm, 3, 3), Eh/Bohr^2
except RuntimeError as err:
    if 'Krylov' not in str(err):
        raise
    print(f'CPHF did not converge in {HESS_MAX_CYCLE} Krylov iterations with level shift '
          f'{HESS_LEVEL_SHIFT}; retrying once with level shift {HESS_RETRY_LEVEL_SHIFT}',
          flush=True)
    run_hessian.level_shift = HESS_RETRY_LEVEL_SHIFT
    hess_raw = run_hessian.kernel()
print(f'Hessian wall {time.time() - t0:.0f} s')

banner('5. SUM-RULE CHECK, REPAIR AND HARMONIC FREQUENCY ANALYSIS')
viol_raw = translational_sum_rule(hess_raw)
print('translational sum rule, raw Hessian, max |sum_q H(p,q)| per atom (Eh/Bohr^2):')
print('  ' + '  '.join(f'{s}{i}: {v:.2e}' for i, (s, v) in enumerate(zip(symbols, viol_raw))))
diag_scale = float(numpy.abs(numpy.einsum('ppxx->px', hess_raw)).max())
print(f'  worst atom relative to the largest diagonal element: {viol_raw.max() / diag_scale:.1e}')
if SUM_RULE_REPAIR:
    hess = enforce_translational_sum_rule(hess_raw)
    viol_fix = translational_sum_rule(hess)
    print(f'repaired Hessian: max violation {viol_fix.max():.1e} Eh/Bohr^2')
else:
    hess = hess_raw
mass = numpy.asarray(new_mol.mass, dtype=float)
rotor = _get_rotor_type(rotation_const(mass, new_mol.atom_coords()))
ntr = 5 if rotor == 'LINEAR' else 6
print(f'rotor type {rotor}: {ntr} translational/rotational modes, '
      f'{3 * new_mol.natm - ntr} vibrations expected')
freqs_raw = harmonic_frequencies(run_hessian, new_mol, hess_raw)
_, vib_raw = split_tr(freqs_raw, ntr)
freqs = harmonic_frequencies(run_hessian, new_mol, hess)
tr, vib = split_tr(freqs, ntr)
print('raw Hessian, all 3N modes     : ' + fmt_modes(freqs_raw))
print('raw Hessian, vibrations       : ' + fmt_modes(vib_raw))
if SUM_RULE_REPAIR:
    print('repaired Hessian, all 3N modes: ' + fmt_modes(freqs))
    print('repaired Hessian, vibrations  : ' + fmt_modes(vib))
proj = run_hessian.harmonic_analysis(new_mol, hess, imaginary_freq=False,
                                     intensity=False)['freq_wavenumber']
proj = numpy.sort(numpy.asarray(proj, dtype=float))
print('cross-check, PySCF projection on the ' + ('repaired' if SUM_RULE_REPAIR else 'raw')
      + ' Hessian (cm^-1): ' + fmt_modes(proj))
numpy.savez(f'{STEM}.hessian.npz', hessian_raw=hess_raw, hessian=hess,
            sum_rule_raw=viol_raw, sum_rule_repair=SUM_RULE_REPAIR,
            freq_raw_all=freqs_raw, freq_raw_vib=vib_raw, freq_all=freqs, freq_vib=vib,
            freq_pyscf_projected=proj, coords_angstrom=coords_eq,
            symbols=numpy.array(symbols), mass_amu=mass, e_sp=e_sp, e_start=e_start,
            xc=XC, basis=BASIS, nuc_basis=NUC_BASIS, ntr=ntr, rotor=rotor)

banner('6. SUMMARY')
print(f'method                        : CNEO-DFT (pyscf.neo.{type(new_mf).__name__}, '
      f'constrained nuclear-electronic orbital DFT)')
print(f'electronic xc functional      : {XC}')
print(f'quantum nuclei                : {", ".join(quantum_nuclei(new_mol))}  '
      f'({new_mol.nuc_num} of {new_mol.natm} nuclei), protonic basis {new_mol.nuclear_basis}')
print(f'epc functional                : {EPC if EPC is not None else "none"}')
print(f'electronic basis              : {BASIS}')
print(f'nuclear basis                 : {new_mol.nuclear_basis}')
print('nuclear masses (amu)          : '
      + ', '.join(f'{s}{i} {m:.6f}' for i, (s, m) in enumerate(zip(symbols, mass))))
print(f'SCF                           : conv_tol {SCF_CONV_TOL:g}, conv_tol_grad {SCF_CONV_TOL_GRAD:g}, '
      f'grid level {GRID_LEVEL}, grid response {GRID_RESPONSE}')
print(f'optimizer                     : geomeTRIC {OPT_PARAMS}; '
      f'converged={opt.converged} after {n_steps} gradient evaluations')
print(f'Hessian CPHF                  : conv_tol_cpscf {CPSCF_CONV_TOL:g}, max_cycle {HESS_MAX_CYCLE}, '
      f'level shift used {run_hessian.level_shift}')
print(f'Hessian sum rule (raw)        : worst atom {symbols[int(viol_raw.argmax())]}{int(viol_raw.argmax())} '
      f'{viol_raw.max():.2e} Eh/Bohr^2 ({viol_raw.max() / diag_scale:.1e} of the largest diagonal element)')
print(f'Hessian repair applied        : {SUM_RULE_REPAIR}')
print('final optimized geometry (Angstrom):')
print('\n'.join('  ' + line for line in geometry_lines(symbols, coords_eq)))
print(f'key distances (Angstrom)      : N...Cl {r_NCl:.3f}   N...H(Cl) {r_NH:.3f}   H(C)...Cl {r_HCl:.3f}')
print(f'final single point energy     : {e_sp:.10f} Eh')
print(f'energy at starting geometry   : {e_start:.10f} Eh   (change {e_sp - e_start:+.3e} Eh)')
n_imag_raw = int(numpy.sum(vib_raw < 0))
n_imag = int(numpy.sum(vib < 0))
print(f'imaginary vibrational modes   : raw Hessian {n_imag_raw}, '
      + (f'repaired Hessian {n_imag}' if SUM_RULE_REPAIR else 'no repair')
      + '   -> ' + ('minimum' if n_imag == 0 else f'saddle point of order {n_imag}'))
print('.....................')
print('Ascending, negative = imaginary' + ('  (repaired Hessian)' if SUM_RULE_REPAIR else ''))
print(f'{"mode":>4} {"freq (cm^-1)":>13}')
for i, f in enumerate(freqs):
    print(f'{i:>4d} {f:>13.2f}' + ('   TR' if i in tr else ''))
print('.....................')
print(f'Dropping TR modes ({ntr}, rotor type {rotor})')
for i, f in enumerate(vib, 1):
    tag = '  imaginary' if f < 0 else ''
    print(f'  {i:>2d}  {abs(f):9.1f}{tag}')
print('.....................')
print(f'total wall time {time.time() - t_start:.0f} s')
