#!/usr/bin/env python
"""
HCN...HF dimer, global min: CNEO-DFT/PW91 aug-cc-pVQZ re-optimization, Hessian and harmonic frequencies

System           : hydrogen cyanide / hydrogen fluoride dimer,
                   linear H-C#N...H-F, HF the hydrogen-bond donor and N the acceptor (global minimum)
Method           : CNEO-DFT (pyscf.neo.CDFT), electronic xc = PW91, no EPC
Quantum nuclei   : every hydrogen (atoms 0 and 3), protonic basis PB4-D
Electronic basis : aug-cc-pvqz
Starting point   : final geometry of the February 2026 PW91/aug-cc-pVQZ global_min run (optimizer converged in 7 steps), re-optimized here

Workflow
  1. tight CNEO-DFT SCF at the starting geometry
  2. geomeTRIC re-optimization with the analytic CNEO-DFT gradient
     (GAU_TIGHT criteria, net force/torque projected out, grid response on)
  3. single-point SCF at the optimized geometry
  4. analytic CNEO-DFT Hessian
  5. harmonic frequencies: all 3N modes, then translations/rotations dropped
  6. summary

Needs the theorychemyang/pyscf fork at version 2.14 or later (its
thermo.rotation_const zeroes the rounding-level moment of inertia of a
linear molecule, so the rotor type is classified correctly) and geomeTRIC.
Outputs next to the log: <stem>.traj.xyz, <stem>.opt.xyz, <stem>.hessian.npz.

Generated by make_inputs.py on 2026-09-18 from geometries/hcn_hf_start_geometries.xyz;
edit the generator, not this file.
"""
import os
import sys
import time

import numpy
import pyscf
from pyscf import neo
from pyscf.geomopt.geometric_solver import GeometryOptimizer
from pyscf.hessian.thermo import rotation_const, _get_rotor_type

# ----------------------------------------------------------------------------
# Settings
# ----------------------------------------------------------------------------
XC = 'pw91'                     # electronic exchange-correlation functional (PySCF/libxc keyword)
EPC = None                     # electron-proton correlation functional; None = off
BASIS = 'aug-cc-pvqz'               # electronic basis on every atom
NUC_BASIS = 'pb4d'             # protonic basis
QUANTUM_NUC = ['H']            # every hydrogen nucleus treated quantum mechanically
CHARGE = 0
VERBOSE = 4
MAX_MEMORY = int(os.environ.get('PYSCF_MAX_MEMORY', 16000))   # MB

# SCF. The nuclear-gradient error is first order in the SCF orbital-gradient
# residual, so the SCF has to be converged well below the optimizer criteria.
SCF_CONV_TOL = 1e-11           # Eh
SCF_CONV_TOL_GRAD = 1e-6       # orbital gradient; the default sqrt(conv_tol) would be 3e-6
SCF_MAX_CYCLE = 200
CPSCF_CONV_TOL = 1e-10         # coupled-perturbed SCF for the Hessian (default 1e-8)
GRID_LEVEL = 5                 # electronic DFT grid (PySCF default 3); set on components['e']
GRID_RESPONSE = True           # grid-weight derivatives in the gradient (only allowed with EPC off)

# Geometry optimization (geomeTRIC through pyscf.geomopt)
OPT_MAX_STEPS = 200            # a 5-atom complex that is not done in 200 steps is stuck in noise
OPT_PARAMS = {
    'convergence_set': 'GAU_TIGHT',   # grms 1e-5, gmax 1.5e-5 Eh/Bohr; drms 4e-5, dmax 6e-5 Angstrom
    'convergence_energy': 1e-8,       # Eh, overrides the set's 1e-6
    'subfrctor': 2,                   # always project net force and torque out of the gradient
}
STOP_IF_OPT_FAILS = True       # do not spend a Hessian on an unconverged geometry

HESS_MAX_CYCLE = 200           # CNEO-CPHF iterations (fork default 100)

STEM = os.path.splitext(os.path.basename(__file__))[0]

# Starting geometry, Angstrom, atom order H C N H F.
# February 2026 PW91/aug-cc-pVQZ global_min final geometry (optimizer converged in 7 steps).
START_GEOM = """
H        0.00000000      -0.00000000      -3.01944286
C       -0.00000000      -0.00000000      -1.92087678
N       -0.00000000      -0.00000000      -0.76908333
H       -0.00000000       0.00000000       0.96251560
F        0.00000000       0.00000000       1.93863943
"""


# ----------------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------------
def banner(title):
    line = '-' * 72
    print(f'\n{line}\n{title}\n{line}', flush=True)


def build_mol(atom):
    return neo.M(atom=atom, basis=BASIS, nuc_basis=NUC_BASIS,
                 quantum_nuc=QUANTUM_NUC, charge=CHARGE, unit='Angstrom',
                 verbose=VERBOSE, max_memory=MAX_MEMORY)


def build_mf(mol):
    mf = neo.CDFT(mol, xc=XC, epc=EPC)
    mf.conv_tol = SCF_CONV_TOL
    mf.conv_tol_grad = SCF_CONV_TOL_GRAD
    mf.max_cycle = SCF_MAX_CYCLE
    mf.conv_tol_cpscf = CPSCF_CONV_TOL
    mf.components['e'].grids.level = GRID_LEVEL
    return mf


def geometry_lines(symbols, coords_ang):
    return [f'{s:<2s} {x:18.10f} {y:18.10f} {z:18.10f}'
            for s, (x, y, z) in zip(symbols, coords_ang)]


def write_xyz(path, symbols, coords_ang, comment):
    with open(path, 'w') as fh:
        fh.write(f'{len(symbols)}\n{comment}\n')
        fh.write('\n'.join(geometry_lines(symbols, coords_ang)) + '\n')


def quantum_nuclei(mol):
    idx = sorted(int(k[1:]) for k in mol.components if k.startswith('n'))
    return [f'{mol.atom_pure_symbol(i)}{i}' for i in idx]


def harmonic_frequencies(hess_obj, mol, hess):
    """All 3N harmonic frequencies in cm^-1, ascending; negative = imaginary.

    Nothing is projected out, so 5 (linear) or 6 (non-linear) modes are
    numerically ~0 and represent translations/rotations. Masses are
    mol.mass, i.e. the CNEO nuclear masses used in the SCF."""
    res = hess_obj.harmonic_analysis(mol, hess, exclude_trans=False, exclude_rot=False,
                                     imaginary_freq=False, intensity=False)
    return numpy.sort(numpy.asarray(res['freq_wavenumber'], dtype=float))


# ----------------------------------------------------------------------------
# Run
# ----------------------------------------------------------------------------
t_start = time.time()
print(STEM)
print(f'pyscf {pyscf.__version__} from {os.path.dirname(pyscf.__file__)}')
try:
    import geometric
    print(f'geometric {geometric.__version__}')
except Exception:                                       # version string is cosmetic
    pass
print(f'numpy {numpy.__version__}; threads {pyscf.lib.num_threads()}; max_memory {MAX_MEMORY} MB')

banner('1. INITIAL SCF AT THE STARTING GEOMETRY')
mol = build_mol(START_GEOM)
mf = build_mf(mol)
e_start = mf.kernel()
if not mf.converged:
    sys.exit('initial SCF did not converge; stopping')
print(f'E(start) = {e_start:.10f} Eh')

banner('2. GEOMETRY OPTIMIZATION (geomeTRIC)')
grad = mf.nuc_grad_method()
grad.grid_response = GRID_RESPONSE
trajectory = []                                          # (step, E, |grad|, coords in Bohr)


def record_step(envs):
    trajectory.append((envs['self'].cycle, float(envs['energy']),
                       float(numpy.linalg.norm(envs['gradients'])),
                       numpy.array(envs['coords'], dtype=float)))


opt = GeometryOptimizer(grad)
opt.callback = record_step
opt.max_cycle = OPT_MAX_STEPS
opt.params = dict(OPT_PARAMS)
t0 = time.time()
mol_eq = opt.kernel()
n_steps = len(trajectory)
print(f'optimizer converged: {opt.converged}   gradient evaluations: {n_steps}   '
      f'wall {time.time() - t0:.0f} s')

symbols = [mol_eq.atom_pure_symbol(i) for i in range(mol_eq.natm)]
coords_eq = mol_eq.atom_coords(unit='ANG')
with open(f'{STEM}.traj.xyz', 'w') as fh:
    for step, e, gnorm, xyz_bohr in trajectory:
        fh.write(f'{len(symbols)}\nstep {step} E={e:.10f} Eh |grad|={gnorm:.3e} Eh/Bohr\n')
        fh.write('\n'.join(geometry_lines(symbols, xyz_bohr * pyscf.lib.param.BOHR)) + '\n')
write_xyz(f'{STEM}.opt.xyz', symbols, coords_eq,
          f'{XC} {BASIS} pb4d optimized geometry, converged={opt.converged}')
if trajectory:
    print(f'last step: E = {trajectory[-1][1]:.10f} Eh   |grad| = {trajectory[-1][2]:.3e} Eh/Bohr')
print('optimized geometry (Angstrom):')
print('\n'.join('  ' + line for line in geometry_lines(symbols, coords_eq)))
if not opt.converged:
    print(f'WARNING: geomeTRIC did not converge within {OPT_MAX_STEPS} steps under {OPT_PARAMS}')
    if STOP_IF_OPT_FAILS:
        sys.exit('stopping before the Hessian; set STOP_IF_OPT_FAILS = False to proceed anyway')

banner('3. SINGLE POINT AT THE OPTIMIZED GEOMETRY')
new_mol = build_mol([[s, c] for s, c in zip(symbols, coords_eq)])
new_mf = build_mf(new_mol)
e_sp = new_mf.kernel()
if not new_mf.converged:
    sys.exit('single-point SCF at the optimized geometry did not converge; stopping')
print(f'E(optimized) = {e_sp:.10f} Eh')

banner('4. ANALYTIC CNEO-DFT HESSIAN')
t0 = time.time()
run_hessian = new_mf.Hessian()
run_hessian.max_cycle = HESS_MAX_CYCLE
hess = run_hessian.kernel()                              # (natm, natm, 3, 3), Eh/Bohr^2
print(f'Hessian wall {time.time() - t0:.0f} s')
sum_rule = float(numpy.abs(hess.sum(axis=1)).max())
print(f'translational sum rule  max |sum_q H(p,q)| = {sum_rule:.2e} Eh/Bohr^2')

banner('5. HARMONIC FREQUENCY ANALYSIS')
mass = numpy.asarray(new_mol.mass, dtype=float)
rotor = _get_rotor_type(rotation_const(mass, new_mol.atom_coords()))
ntr = 5 if rotor == 'LINEAR' else 6
print(f'rotor type {rotor}: {ntr} translational/rotational modes, '
      f'{3 * new_mol.natm - ntr} vibrations expected')
freqs = harmonic_frequencies(run_hessian, new_mol, hess)
order = numpy.argsort(numpy.abs(freqs))
tr = set(order[:ntr])
vib = numpy.sort(freqs[order[ntr:]])
proj = run_hessian.harmonic_analysis(new_mol, hess, imaginary_freq=False,
                                     intensity=False)['freq_wavenumber']
proj = numpy.sort(numpy.asarray(proj, dtype=float))
print('cross-check, PySCF with translations/rotations projected out (cm^-1):')
print('  ' + '  '.join(f'{f:9.2f}' for f in proj))
numpy.savez(f'{STEM}.hessian.npz', hessian=hess, freq_all=freqs, freq_vib=vib,
            freq_pyscf_projected=proj, coords_angstrom=coords_eq,
            symbols=numpy.array(symbols), mass_amu=mass, e_sp=e_sp, e_start=e_start,
            xc=XC, basis=BASIS, nuc_basis=NUC_BASIS, ntr=ntr, rotor=rotor)

banner('6. SUMMARY')
print(f'method                        : CNEO-DFT (pyscf.neo.{type(new_mf).__name__}, '
      f'constrained nuclear-electronic orbital DFT)')
print(f'electronic xc functional      : {XC}')
print(f'quantum nuclei                : {", ".join(quantum_nuclei(new_mol))}  '
      f'({new_mol.nuc_num} of {new_mol.natm} nuclei), protonic basis {new_mol.nuclear_basis}')
print(f'epc functional                : {EPC if EPC is not None else "none"}')
print(f'electronic basis              : {BASIS}')
print(f'nuclear basis                 : {new_mol.nuclear_basis}')
print('nuclear masses (amu)          : '
      + ', '.join(f'{s}{i} {m:.6f}' for i, (s, m) in enumerate(zip(symbols, mass))))
print(f'SCF                           : conv_tol {SCF_CONV_TOL:g}, conv_tol_grad {SCF_CONV_TOL_GRAD:g}, '
      f'grid level {GRID_LEVEL}, grid response {GRID_RESPONSE}')
print(f'optimizer                     : geomeTRIC {OPT_PARAMS}; '
      f'converged={opt.converged} after {n_steps} gradient evaluations')
print('final optimized geometry (Angstrom):')
print('\n'.join('  ' + line for line in geometry_lines(symbols, coords_eq)))
print(f'final single point energy     : {e_sp:.10f} Eh')
print(f'energy at starting geometry   : {e_start:.10f} Eh   (change {e_sp - e_start:+.3e} Eh)')
n_imag = int(numpy.sum(vib < 0))
print(f'imaginary vibrational modes   : {n_imag}   -> '
      + ('minimum' if n_imag == 0 else f'saddle point of order {n_imag}'))
print('.....................')
print('Ascending, negative = imaginary')
print(f'{"mode":>4} {"freq (cm^-1)":>13}')
for i, f in enumerate(freqs):
    print(f'{i:>4d} {f:>13.2f}' + ('   TR' if i in tr else ''))
print('.....................')
print(f'Dropping TR modes ({ntr}, rotor type {rotor})')
for i, f in enumerate(vib, 1):
    tag = '  imaginary' if f < 0 else ''
    print(f'  {i:>2d}  {abs(f):9.1f}{tag}')
print('.....................')
print(f'total wall time {time.time() - t_start:.0f} s')
