#!/usr/bin/env python
"""
HF/HCl dimer, hcl donor: DFT/PW91 aug-cc-pVQZ re-optimization, Hessian and harmonic frequencies (classical nuclei)

System           : hydrogen fluoride / hydrogen chloride dimer,
                   Cl-H...F-H, HCl the hydrogen-bond donor and F the acceptor, HF tilted (a minimum 0.3 to 0.7 kcal/mol above the HF-donor isomer in the April 2026 DFT runs)
Method           : conventional Kohn-Sham DFT (pyscf.dft.RKS), all nuclei classical,
                   xc = PW91
Electronic basis : aug-cc-pvqz
Starting point   : final geometry of the April 2026 conventional-DFT PW91/aug-cc-pVQZ run for this isomer (optimizer converged in 13 steps (April 2026 conventional-DFT 'local_min' run)), re-optimized here

Workflow
  1. tight DFT SCF at the starting geometry
  2. geomeTRIC re-optimization with the analytic DFT gradient
     (GAU_TIGHT criteria, net force/torque projected out, grid response on)
  3. single-point SCF at the optimized geometry
  4. analytic DFT Hessian (300 CPHF iterations, level-shift retry)
  5. translational sum-rule check of the Hessian and repair of its diagonal
     blocks; harmonic frequencies from the raw and the repaired Hessian
  6. summary

This is the classical-nuclei counterpart of the CNEO-DFT input of the same
name in ../hf_hcl/: same functional, basis, SCF/CPHF tolerances, grid level
and 400-shell halogen grids, grid response, optimizer criteria and step
cap, Hessian settings and sum-rule check, so that CNEO-DFT minus DFT
differences isolate the nuclear quantum effect. The harmonic analysis uses
PySCF's isotope-averaged atomic masses (H 1.008, F 18.998, Cl 35.45 u),
the standard convention for conventional DFT. The CNEO-DFT inputs use the
nuclear mass 1.007276 u for their quantum protons; the 0.07 % mass
difference changes a frequency by at most 0.04 %, about 1 cm^-1 at
3000 cm^-1.

Why the dense halogen grids and the repair: PySCF's RKS Hessian, like the
NEO one, holds the DFT grid fixed (no grid response for GGA functionals),
so the exchange-correlation part violates the translational sum rule by the
quadrature stiffness of each atom's density on its own radial grid. In the
April 2026 DFT runs (grid level 9, 200 radial shells) the chlorine violation
was below 6e-5 Eh/Bohr^2 and the fluorine violation below 2.1e-4; all 30
runs are minima raw and repaired and the repair moved no vibration by more
than 9 cm^-1 (median 0.5). At grid level 5 (F 105, Cl 110 shells) the defect
is larger: the April CNEO-DFT HF/HCl Hessians at level 3 carried 0.07 to
0.42 Eh/Bohr^2 on chlorine, and their raw aug-cc-pVDZ and aug-cc-pVQZ
spectra showed a spurious 54i to 307i mode. The HCN...HBr probe showed the
defect is radial quadrature error that 400 shells remove and that the
repair reproduces the converged spectrum to 0.1 cm^-1. These inputs
therefore put 400 radial shells on both halogens (ATOM_GRIDS, as in
../hf_hcl/) and keep the repair as a check; both spectra are printed.

Needs PySCF 2.14 or later (the theorychemyang fork is fine) and geomeTRIC.
Outputs next to the log: <stem>.traj.xyz, <stem>.opt.xyz, <stem>.hessian.npz.

Generated by make_inputs.py on 2026-09-20 from geometries/hf_hcl_dft_start_geometries.xyz;
edit the generator, not this file.
"""
import os
import sys
import time

import numpy
import pyscf
from pyscf import gto, dft
from pyscf.geomopt.geometric_solver import GeometryOptimizer
from pyscf.hessian import thermo
from pyscf.hessian.thermo import rotation_const, _get_rotor_type

# ----------------------------------------------------------------------------
# Settings (identical to ../hf_hcl/ CNEO-DFT inputs where a counterpart exists)
# ----------------------------------------------------------------------------
XC = 'pw91'                     # exchange-correlation functional (PySCF/libxc keyword)
BASIS = 'aug-cc-pvqz'               # electronic basis on every atom
CHARGE = 0
VERBOSE = 4
MAX_MEMORY = int(os.environ.get('PYSCF_MAX_MEMORY', 16000))   # MB

# SCF. The nuclear-gradient error is first order in the SCF orbital-gradient
# residual, so the SCF has to be converged well below the optimizer criteria.
SCF_CONV_TOL = 1e-11           # Eh
SCF_CONV_TOL_GRAD = 1e-6       # orbital gradient; the default sqrt(conv_tol) would be 3e-6
SCF_MAX_CYCLE = 200
CPSCF_CONV_TOL = 1e-9          # coupled-perturbed SCF for the Hessian (default 1e-8)
GRID_LEVEL = 5                 # DFT grid (PySCF default 3): H 70 x 590, F 105 x 770, Cl 110 x 770
ATOM_GRIDS = {'F': (400, 770), 'Cl': (400, 770)}   # (radial shells, Lebedev points) per element: 400 radial
                               # shells on both halogens, matching ../hf_hcl/; the fixed-grid Hessian
                               # needs them (see the docstring). {} = the level-5 table everywhere.
GRID_RESPONSE = True           # grid-weight derivatives in the gradient

# Geometry optimization (geomeTRIC through pyscf.geomopt)
OPT_MAX_STEPS = 200            # a 4-atom complex that is not done in 200 steps is stuck in noise
OPT_PARAMS = {
    'convergence_set': 'GAU_TIGHT',   # grms 1e-5, gmax 1.5e-5 Eh/Bohr; drms 4e-5, dmax 6e-5 Angstrom
    'convergence_energy': 1e-8,       # Eh, overrides the set's 1e-6
    'subfrctor': 2,                   # always project net force and torque out of the gradient
}
STOP_IF_OPT_FAILS = True       # do not spend a Hessian on an unconverged geometry

# The coupled-perturbed equations are solved with PySCF's Krylov solver, which
# raises RuntimeError when it reaches max_cycle (RKS default 50; the April DFT
# Hessians needed 12 to 13 iterations, the CNEO ones far more). Allow far more
# iterations and, if the solver still fails, retry once with a level shift on
# the preconditioner (a convergence aid that does not change the converged
# solution).
HESS_MAX_CYCLE = 300           # CPHF Krylov iterations
HESS_LEVEL_SHIFT = 0.0         # Eh, added to the orbital-energy denominators
HESS_RETRY_LEVEL_SHIFT = 0.2   # Eh, used for the one automatic retry

# Hessian repair: enforce the translational sum rule sum_q H(p,q) = 0 by
# resetting each diagonal block. The frequency tables below use the repaired
# Hessian; the raw spectrum is printed alongside for comparison.
SUM_RULE_REPAIR = True

# Nuclear masses for the harmonic analysis: PySCF's isotope-averaged atomic
# masses (mol.atom_mass_list(isotope_avg=True); H 1.008 u), the standard
# convention for conventional DFT and the one PySCF's thermo module uses by
# default. The CNEO mass convention of the CNEO-DFT inputs is not used here.

STEM = os.path.splitext(os.path.basename(__file__))[0]

# Starting geometry, Angstrom, atom order H0 F1 H2 Cl3 (H0-F1 is HF, H2-Cl3 is HCl).
# PW91/aug-cc-pVQZ hcl_donor: optimizer converged in 13 steps (April 2026 conventional-DFT 'local_min' run).
START_GEOM = """
H       -2.40224879      -0.80176551      -0.00000000
F       -2.09061310       0.07655737       0.00000000
H       -0.11278543       0.15370344      -0.00000000
Cl       1.17243024      -0.02514972      -0.00000000
"""


# ----------------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------------
def banner(title):
    line = '-' * 72
    print(f'\n{line}\n{title}\n{line}', flush=True)


def build_mol(atom):
    return gto.M(atom=atom, basis=BASIS, charge=CHARGE, unit='Angstrom',
                 verbose=VERBOSE, max_memory=MAX_MEMORY)


def build_mf(mol):
    mf = dft.RKS(mol, xc=XC)
    mf.conv_tol = SCF_CONV_TOL
    mf.conv_tol_grad = SCF_CONV_TOL_GRAD
    mf.max_cycle = SCF_MAX_CYCLE
    mf.conv_tol_cpscf = CPSCF_CONV_TOL
    mf.grids.level = GRID_LEVEL
    if ATOM_GRIDS:
        mf.grids.atom_grid = {k: tuple(v) for k, v in ATOM_GRIDS.items()}
    return mf


def nuclear_masses(mol):
    """Isotope-averaged atomic masses (amu) for the harmonic analysis."""
    return numpy.asarray(mol.atom_mass_list(isotope_avg=True), dtype=float)


def geometry_lines(symbols, coords_ang):
    return [f'{s:<2s} {x:18.10f} {y:18.10f} {z:18.10f}'
            for s, (x, y, z) in zip(symbols, coords_ang)]


def write_xyz(path, symbols, coords_ang, comment):
    with open(path, 'w') as fh:
        fh.write(f'{len(symbols)}\n{comment}\n')
        fh.write('\n'.join(geometry_lines(symbols, coords_ang)) + '\n')


def grid_report(mol, grids):
    """Lines describing the DFT grid actually used (per element and in total)."""
    from pyscf.dft import gen_grid
    name = lambda f: getattr(f, '__name__', str(f))
    lines = [f'level {grids.level}; radial scheme {name(grids.radi_method)}; '
             f'partition {name(grids.becke_scheme)}; pruning {name(grids.prune)}']
    seen = []
    for ia in range(mol.natm):
        symb = mol.atom_pure_symbol(ia)
        if symb in seen:
            continue
        seen.append(symb)
        cfg = (grids.atom_grid or {}).get(symb)
        if cfg is not None:
            n_rad, n_ang, src = cfg[0], cfg[1], 'explicit atom_grid'
        else:
            try:
                chg = mol.atom_charge(ia)
                n_rad = gen_grid._default_rad(chg, grids.level)
                n_ang = gen_grid._default_ang(chg, grids.level)
            except Exception:                            # table lookup is cosmetic
                n_rad = n_ang = '?'
            src = f'level-{grids.level} table'
        lines.append(f'{symb}: {n_rad} radial shells x {n_ang} angular points before pruning ({src})')
    npts = grids.weights.size if getattr(grids, 'weights', None) is not None else 0
    lines.append(f'total grid points after pruning: {npts}')
    return lines


def translational_sum_rule(hess):
    """Per-atom max |sum_q H(p,q,x,y)| in Eh/Bohr^2; exactly zero for an exact Hessian."""
    return numpy.abs(hess.sum(axis=1)).reshape(hess.shape[0], -1).max(axis=1)


def enforce_translational_sum_rule(hess):
    """Reset each diagonal block H(p,p) = -sum_{q!=p} H(p,q), then re-symmetrize."""
    natm = hess.shape[0]
    fixed = hess.copy()
    for p in range(natm):
        off = hess[p].sum(axis=0) - hess[p, p]
        fixed[p, p] = -off
    return 0.5 * (fixed + fixed.transpose(1, 0, 3, 2))


def harmonic_frequencies(mol, hess, mass):
    """All 3N harmonic frequencies in cm^-1, ascending; negative = imaginary.

    Nothing is projected out, so 5 (linear) or 6 (non-linear) modes are
    numerically ~0 and represent translations/rotations."""
    res = thermo.harmonic_analysis(mol, hess, exclude_trans=False, exclude_rot=False,
                                   imaginary_freq=False, mass=mass)
    return numpy.sort(numpy.asarray(res['freq_wavenumber'], dtype=float))


def split_tr(freqs, ntr):
    order = numpy.argsort(numpy.abs(freqs))
    return set(order[:ntr]), numpy.sort(freqs[order[ntr:]])


def fmt_modes(fs):
    return ', '.join((f'{-f:.1f}i' if f < 0 else f'{f:.1f}') for f in fs)


# ----------------------------------------------------------------------------
# Run
# ----------------------------------------------------------------------------
t_start = time.time()
print(STEM)
print(f'pyscf {pyscf.__version__} from {os.path.dirname(pyscf.__file__)}')
try:
    import geometric
    print(f'geometric {geometric.__version__}')
except Exception:                                       # version string is cosmetic
    pass
print(f'numpy {numpy.__version__}; threads {pyscf.lib.num_threads()}; max_memory {MAX_MEMORY} MB')

banner('1. INITIAL SCF AT THE STARTING GEOMETRY')
mol = build_mol(START_GEOM)
mf = build_mf(mol)
e_start = mf.kernel()
if not mf.converged:
    sys.exit('initial SCF did not converge; stopping')
print(f'E(start) = {e_start:.10f} Eh')
print('DFT grid: ' + '; '.join(grid_report(mol, mf.grids)))

banner('2. GEOMETRY OPTIMIZATION (geomeTRIC)')
grad = mf.nuc_grad_method()
grad.grid_response = GRID_RESPONSE
trajectory = []                                          # (step, E, |grad|, coords in Bohr)


def record_step(envs):
    trajectory.append((envs['self'].cycle, float(envs['energy']),
                       float(numpy.linalg.norm(envs['gradients'])),
                       numpy.array(envs['coords'], dtype=float)))


opt = GeometryOptimizer(grad)
opt.callback = record_step
opt.max_cycle = OPT_MAX_STEPS
opt.params = dict(OPT_PARAMS)
t0 = time.time()
mol_eq = opt.kernel()
n_steps = len(trajectory)
print(f'optimizer converged: {opt.converged}   gradient evaluations: {n_steps}   '
      f'wall {time.time() - t0:.0f} s')

symbols = [mol_eq.atom_pure_symbol(i) for i in range(mol_eq.natm)]
coords_eq = mol_eq.atom_coords(unit='ANG')
with open(f'{STEM}.traj.xyz', 'w') as fh:
    for step, e, gnorm, xyz_bohr in trajectory:
        fh.write(f'{len(symbols)}\nstep {step} E={e:.10f} Eh |grad|={gnorm:.3e} Eh/Bohr\n')
        fh.write('\n'.join(geometry_lines(symbols, xyz_bohr * pyscf.lib.param.BOHR)) + '\n')
write_xyz(f'{STEM}.opt.xyz', symbols, coords_eq,
          f'DFT {XC} {BASIS} optimized geometry, converged={opt.converged}')
if trajectory:
    print(f'last step: E = {trajectory[-1][1]:.10f} Eh   |grad| = {trajectory[-1][2]:.3e} Eh/Bohr')
print('optimized geometry (Angstrom):')
print('\n'.join('  ' + line for line in geometry_lines(symbols, coords_eq)))


def _d(i, j):
    return float(numpy.linalg.norm(coords_eq[i] - coords_eq[j]))


def _ang(i, j, k):
    u, v = coords_eq[i] - coords_eq[j], coords_eq[k] - coords_eq[j]
    return float(numpy.degrees(numpy.arccos(numpy.clip(u @ v / (numpy.linalg.norm(u) * numpy.linalg.norm(v)), -1, 1))))


r_HF, r_HCl, r_H0Cl, r_H2F, r_FCl = _d(0, 1), _d(2, 3), _d(0, 3), _d(2, 1), _d(1, 3)
if r_H0Cl < r_H2F:
    DONOR, a_XHY, a_tilt = 'HF (F-H...Cl-H)', _ang(1, 0, 3), _ang(0, 3, 2)
else:
    DONOR, a_XHY, a_tilt = 'HCl (Cl-H...F-H)', _ang(3, 2, 1), _ang(2, 1, 0)
KEY = (f'H0-F1 {r_HF:.3f}   H2-Cl3 {r_HCl:.3f}   H0...Cl3 {r_H0Cl:.3f}   H2...F1 {r_H2F:.3f}   '
       f'F1...Cl3 {r_FCl:.3f} Angstrom;   donor {DONOR};   X-H...Y {a_XHY:.1f}   H...Y-H {a_tilt:.1f} deg')
print('key geometry: ' + KEY)
if r_HF > 1.3 or r_HCl > 1.6:
    print('WARNING: H0-F1 or H2-Cl3 is no longer a covalent bond; the atoms have migrated')
if r_FCl > 6.0:
    print('WARNING: the monomers have separated by more than 6 Angstrom; this is not a bound complex')
if not opt.converged:
    print(f'WARNING: geomeTRIC did not converge within {OPT_MAX_STEPS} steps under {OPT_PARAMS}')
    if STOP_IF_OPT_FAILS:
        sys.exit('stopping before the Hessian; set STOP_IF_OPT_FAILS = False to proceed anyway')

banner('3. SINGLE POINT AT THE OPTIMIZED GEOMETRY')
new_mol = build_mol([[s, c] for s, c in zip(symbols, coords_eq)])
new_mf = build_mf(new_mol)
e_sp = new_mf.kernel()
if not new_mf.converged:
    sys.exit('single-point SCF at the optimized geometry did not converge; stopping')
print(f'E(optimized) = {e_sp:.10f} Eh')

banner('4. ANALYTIC DFT HESSIAN')
t0 = time.time()
run_hessian = new_mf.Hessian()
run_hessian.max_cycle = HESS_MAX_CYCLE
run_hessian.level_shift = HESS_LEVEL_SHIFT
run_hessian.verbose = 4                                  # logs 'krylov cycle N  r = ...'
try:
    hess_raw = run_hessian.kernel()                      # (natm, natm, 3, 3), Eh/Bohr^2
except RuntimeError as err:
    if 'Krylov' not in str(err):
        raise
    print(f'CPHF did not converge in {HESS_MAX_CYCLE} Krylov iterations with level shift '
          f'{HESS_LEVEL_SHIFT}; retrying once with level shift {HESS_RETRY_LEVEL_SHIFT}',
          flush=True)
    run_hessian.level_shift = HESS_RETRY_LEVEL_SHIFT
    hess_raw = run_hessian.kernel()
print(f'Hessian wall {time.time() - t0:.0f} s')

banner('5. SUM-RULE CHECK, REPAIR AND HARMONIC FREQUENCY ANALYSIS')
viol_raw = translational_sum_rule(hess_raw)
print('translational sum rule, raw Hessian, max |sum_q H(p,q)| per atom (Eh/Bohr^2):')
print('  ' + '  '.join(f'{s}{i}: {v:.2e}' for i, (s, v) in enumerate(zip(symbols, viol_raw))))
diag_scale = float(numpy.abs(numpy.einsum('ppxx->px', hess_raw)).max())
print(f'  worst atom relative to the largest diagonal element: {viol_raw.max() / diag_scale:.1e}')
if SUM_RULE_REPAIR:
    hess = enforce_translational_sum_rule(hess_raw)
    viol_fix = translational_sum_rule(hess)
    print(f'repaired Hessian: max violation {viol_fix.max():.1e} Eh/Bohr^2')
else:
    hess = hess_raw
mass = nuclear_masses(new_mol)
rotor = _get_rotor_type(rotation_const(mass, new_mol.atom_coords()))
ntr = 5 if rotor == 'LINEAR' else 6
print(f'rotor type {rotor}: {ntr} translational/rotational modes, '
      f'{3 * new_mol.natm - ntr} vibrations expected')
freqs_raw = harmonic_frequencies(new_mol, hess_raw, mass)
_, vib_raw = split_tr(freqs_raw, ntr)
freqs = harmonic_frequencies(new_mol, hess, mass)
tr, vib = split_tr(freqs, ntr)
print('raw Hessian, all 3N modes     : ' + fmt_modes(freqs_raw))
print('raw Hessian, vibrations       : ' + fmt_modes(vib_raw))
if SUM_RULE_REPAIR:
    print('repaired Hessian, all 3N modes: ' + fmt_modes(freqs))
    print('repaired Hessian, vibrations  : ' + fmt_modes(vib))
proj = thermo.harmonic_analysis(new_mol, hess, imaginary_freq=False, mass=mass)['freq_wavenumber']
proj = numpy.sort(numpy.asarray(proj, dtype=float))
print('cross-check, PySCF projection on the ' + ('repaired' if SUM_RULE_REPAIR else 'raw')
      + ' Hessian (cm^-1): ' + fmt_modes(proj))
numpy.savez(f'{STEM}.hessian.npz', hessian_raw=hess_raw, hessian=hess,
            sum_rule_raw=viol_raw, sum_rule_repair=SUM_RULE_REPAIR,
            freq_raw_all=freqs_raw, freq_raw_vib=vib_raw, freq_all=freqs, freq_vib=vib,
            freq_pyscf_projected=proj, coords_angstrom=coords_eq,
            symbols=numpy.array(symbols), mass_amu=mass,
            mass_convention='isotope-averaged atomic masses', e_sp=e_sp, e_start=e_start,
            xc=XC, basis=BASIS, ntr=ntr, rotor=rotor)

banner('6. SUMMARY')
print(f'method                        : conventional DFT (pyscf.dft.{type(new_mf).__name__}), '
      f'all {new_mol.natm} nuclei classical')
print(f'xc functional                 : {XC}')
print('quantum nuclei                : none')
print(f'electronic basis              : {BASIS}')
print('nuclear masses (amu)          : isotope-averaged atomic masses (PySCF default); '
      + ', '.join(f'{s}{i} {m:.6f}' for i, (s, m) in enumerate(zip(symbols, mass))))
print(f'SCF                           : conv_tol {SCF_CONV_TOL:g}, conv_tol_grad {SCF_CONV_TOL_GRAD:g}, '
      f'grid response {GRID_RESPONSE}')
grid_lines = grid_report(new_mol, new_mf.grids)
print('DFT grid                      : ' + grid_lines[0])
for line in grid_lines[1:]:
    print('                                ' + line)
print(f'atom grid overrides           : {ATOM_GRIDS if ATOM_GRIDS else "none (level table everywhere)"}')
print(f'optimizer                     : geomeTRIC {OPT_PARAMS}; '
      f'converged={opt.converged} after {n_steps} gradient evaluations')
print(f'Hessian CPHF                  : conv_tol_cpscf {CPSCF_CONV_TOL:g}, max_cycle {HESS_MAX_CYCLE}, '
      f'level shift used {run_hessian.level_shift}')
print(f'Hessian sum rule (raw)        : worst atom {symbols[int(viol_raw.argmax())]}{int(viol_raw.argmax())} '
      f'{viol_raw.max():.2e} Eh/Bohr^2 ({viol_raw.max() / diag_scale:.1e} of the largest diagonal element)')
print(f'Hessian repair applied        : {SUM_RULE_REPAIR}')
print('final optimized geometry (Angstrom):')
print('\n'.join('  ' + line for line in geometry_lines(symbols, coords_eq)))
print('key geometry                  : ' + KEY)
print(f'final single point energy     : {e_sp:.10f} Eh')
print(f'energy at starting geometry   : {e_start:.10f} Eh   (change {e_sp - e_start:+.3e} Eh)')
n_imag_raw = int(numpy.sum(vib_raw < 0))
n_imag = int(numpy.sum(vib < 0))
print(f'imaginary vibrational modes   : raw Hessian {n_imag_raw}, '
      + (f'repaired Hessian {n_imag}' if SUM_RULE_REPAIR else 'no repair')
      + '   -> ' + ('minimum' if n_imag == 0 else f'saddle point of order {n_imag}'))
print('.....................')
print('Ascending, negative = imaginary' + ('  (repaired Hessian)' if SUM_RULE_REPAIR else '')
      + '  (isotope-averaged atomic masses)')
print(f'{"mode":>4} {"freq (cm^-1)":>13}')
for i, f in enumerate(freqs):
    print(f'{i:>4d} {f:>13.2f}' + ('   TR' if i in tr else ''))
print('.....................')
print(f'Dropping TR modes ({ntr}, rotor type {rotor})')
for i, f in enumerate(vib, 1):
    tag = '  imaginary' if f < 0 else ''
    print(f'  {i:>2d}  {abs(f):9.1f}{tag}')
print('.....................')
print(f'total wall time {time.time() - t_start:.0f} s')
